### PR TITLE
feat: use default `discord_client_id`

### LINKED ISSUE #46: Built-in client IDs / API keys for Trakt, Discord, and TMDB
### 📝 Provide a description of the new feature

It would be more convenient if Discrakt used preset client IDs for Trakt and Discord. You would not need to do the [Setup](https://github.com/afonsojramos/discrakt#setup) process. Just setup the Trakt user (or a `--user` flag for a no-config process) and run the application.

### ➕ Additional Information

Related to #24

### PR DESCRIPTION
**Pull request by afonsojramos**
## 📑 Description

Partially closes #46. Changes related to Trakt might also be brought into this PR if changes are not too drastic.

## ✅ Checks
- [x] **code:** My pull request adheres to the code style of this project
- [ ] **docs:** Added / updated
- [ ] **tests:** All the tests have passed

## ℹ Additional Information

Please take a look if it makes sense @sitiom @rollingmoai

### CODE REVIEW

**Review by sitiom — CHANGES_REQUESTED** [review]
> Changes related to Trakt might also be brought into this PR if changes are not too drastic.

It would be nice to hardcode the TMDB API key as well (Example: https://github.com/xbmc/xbmc/blob/495a07ad6805ffc17475d6b7181a92ce16d1c01e/addons/metadata.themoviedb.org.python/python/lib/tmdbscraper/tmdbapi.py#L36)

**Comment by afonsojramos** [comment]
@sitiom Interesting 🤔 But that seems to open these API keys to be used outside of their intended use....

**Comment by afonsojramos** [comment]
@sitiom Further investigation proved that it is indeed not prudent that I ship these API keys with the binary as that would be a break of the ToS with TMDB.

**Comment by sitiom** [comment]
Where is it specified? And how come the TMDB scraper addon above from Kodi not break TOS?

**Comment by afonsojramos** [comment]
Best I've found was this tbh: https://www.themoviedb.org/talk/6272acd4a313b812cd7aab5e

But with so many out there... Why not?

**Pull request merged**
