### PR TITLE
Added support for private profiles

### PR DESCRIPTION
**Pull request by lluni**
## 📑 Description

Implements #35 by optionally using OAuth.

## ✅ Checks
- [ ] **code:** My pull request adheres to the code style of this project (I ran `cargo fmt`.)
- [ ] **docs:** Added / updated (Which docs?)
- [ ] **tests:** All the tests have passed (Which tests? I have tested this PR with my own private trakt profile.)

## ℹ Additional Information

This PR adds the following entries to `credentials.ini`:
```ini
[Trakt API]
...
enabledOAuth = false
traktClientSecret =
OAuthAccessToken =
OAuthRefreshToken =
OAuthRefreshTokenExpiresAt =
...
```
If the user wants to enable OAuth, it is expected that they set `enabledOAuth = true` and `traktClientSecret =
<trakt client secret>`, otherwise they can be left as is. The three other fields are set programmatically.

Application flow for using OAuth for the first time:
1. Set both aforementioned values.
2. Log into the automatically opened trakt OAuth website.
3. Paste the displayed OAuth code into the command line.
4. The other tokens are generated automatically and all the following starts of discrakt do not need any interaction.

~~I haven't found a nice way to write the generated tokens back to `credentials.ini`. The straightforward way to loading the whole config, changing the token entries and writing the whole config back to `credentials.ini` results in "ugly" formatting. Maybe writing them to the file "manually" would be better (but somewhat annoying to implement)?~~
The order of the entries in `credentials.ini` is now kept the same when writing the OAuth tokens back to the file (4336736). The only thing left regarding "ugly" formatting is that the spaces around the equal signs are removed when writing the values back to the file, but I haven't found a fix for that.

### CODE REVIEW

**Comment by lluni** [comment]
For the record: I force-pushed because the previous commits didn't have semantic commit messages.

**Comment by afonsojramos** [comment]
Sorry I didn't notice this PR until now! I'll try to review it tomorrow!

**Review by afonsojramos — APPROVED** [review]

**Comment by afonsojramos** [comment]
Thanks for the PR and sorry for the late review, merging in!

**Review by sitiom — COMMENTED** [review]
See https://github.com/afonsojramos/discrakt/issues/46#issuecomment-1980011314

**Pull request merged**
